### PR TITLE
DE14130 - Host deletion might fail with ETag conflict

### PR DESCRIPTION
**Pull request by dbozzato81**
Included retry on ETag mismatch for host deletion

### CODE REVIEW

**Comment by ron-saito** [comment]
I'm wondering if it would be good to use hpe-hcss/quake/pkg/condition/wait.go.  Not sure how to share this lib.gulp....perhaps copy it?

**Comment by dbozzato81** [comment]
> I'm wondering if it would be good to use hpe-hcss/quake/pkg/condition/wait.go. Not sure how to share this lib.gulp....perhaps copy it?

Yes we would need to copy it over so we avoid circular dependencies.

**Comment by neilgierman** [comment]
> > I'm wondering if it would be good to use hpe-hcss/quake/pkg/condition/wait.go. Not sure how to share this lib.gulp....perhaps copy it?
> 
> Yes we would need to copy it over so we avoid circular dependencies.

Also it would have to be copied because other people that are building this won't have access to hpe-hcss. Wondering if we should "move" that function from quake to hpegl-metal-client and then both terraform resources and quake can pull from a single source. hpe-hcss can pull from hewlettpackard, but not the reverse.

**Comment by dbozzato81** [comment]
I don’t think moving the condition pkg under hpegl-metal-client would make sense since the client is dealing with project API while the pkg could be used for any REST endpoint. In addition I think that the condition pkg provides a lot more abstractions of what we really need for the TF provider.

**Comment by neilgierman** [comment]
> I don’t think moving the condition pkg under hpegl-metal-client would make sense since the client is dealing with project API while the pkg could be used for any REST endpoint. In addition I think that the condition pkg provides a lot more abstractions of what we really need for the TF provider.

Trying to think of a location where both quake and terraform have access instead of having duplicate code.

**Comment by mchuang3** [comment]
Sorry, a little late to this review.  I think having Client checking ETag error on a Delete doesn't make sense since client doesn't provide Etag when deleting  The ETag is coming from a conflict in the back end trying to add Events to the Host before marking it as deleted.  I think the retry should go to backend code instead.

**Comment by dbozzato81** [comment]
> Sorry, a little late to this review. I think having Client checking ETag error on a Delete doesn't make sense since client doesn't provide Etag when deleting The ETag is coming from a conflict in the back end trying to add Events to the Host before marking it as deleted. I think the retry should go to backend code instead.

Ok make sense. I’ll close this PR and open a new one to fix the defect on the backend.

**Comment by dbozzato81** [comment]
Closing. Defect will be fix on the backend.

**Pull request closed without merging**
